version: '2'
services:
  webapp:
    image: pathwaycommons/app-ui:latest
    container_name: appui_webapp
    ports:
      - "3000:3000" 
    environment:
      ip: "db"      
    links:
      - db
  db:
    container_name: appui_db
    image: rethinkdb:2.3.6
    ports:
      - "8080:8080"   
      - "28015:28015"   