version: '3'
services:
  webapp:
    image: pathwaycommons/app-ui:development
    container_name: appui_webapp
    ports:
      - "9090:3000" 
    environment:
      NODE_ENV: "development"  
      host: "db"
  db:
    container_name: appui_db
    image: rethinkdb:2.3.6
    ports:
      - "8020:8080" 
      - "28015:28015" 